import './jquery.vmodel.init.js';
import './jquery.vmodel.api.js';
import './jquery.vmodel.version.js';
import './jquery.vmodel.end.js';
import './jquery.vmodel.history.js';
import './jquery.vmodel.get.js';
import './jquery.vmodel.delete.js';
import './jquery.vmodel.create.js';
import './jquery.vmodel.fn.js';